version: "3.9"

services:
  db:
    container_name: postgres-db
    image: postgres:13.3-alpine
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
    networks:
      - nodets_network

networks:
  nodets_network:
    driver: bridge
