name: Node.js CI

on:
  push:

jobs:
  checkout_and_install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "./package-lock.json"
      - name: Install dependencies
        run: npm ci
  build:
    runs-on: ubuntu-latest
    needs: checkout_and_install
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "./package-lock.json"
      - name: Build project
        run: npm run build --if-present
